language: python

python:
  - 2.6
  - 2.7
  - 3.3

install: pip install requests pytest httpretty --use-mirrors

script:
  - python setup.py test_units
  - REALHTTP=1 python setup.py test_units
  - python setup.py test_integration

branches:
  only:
    - master
