language: python

python:
  - 2.6
  - 2.7
  - 3.2

install: pip install requests==0.14.1 pytest mock --use-mirrors

script:
  - python setup.py test
  - make prove -C test/integration

branches:
  only:
    - master
