language: python

python:
  - 2.6
  - 2.7
  - 3.3

install: pip install requests pytest httpretty --use-mirrors

script:
  - python setup.py test
  - REALHTTP=1 python setup.py test
  - make prove -C test/integration

branches:
  only:
    - master
