#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
rdd_r
~~~~~

Runner script to invoke rdd command-line tool without installing it first.

"""

import rdd.cli

if __name__ == '__main__':
    rdd.cli.main()
